# Generated by Django 4.2.6 on 2023-10-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payer",
            name="points_given",
            field=models.IntegerField(null=True),
        ),
    ]
