# Generated by Django 4.2.6 on 2023-10-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rewards", "0002_alter_payer_points_given"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payer",
            name="points_given",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
